services:
    dropzoneBundle.form.type.dropzoneS3File:
        class: Evoluta\DropzoneBundle\Form\Type\DropzoneS3FileType
        arguments:
          - "%dropzone_endpoint%"
          - "%dropzone_accessKey%"
          - "%dropzone_secret%"
          - "%dropzone_bucket%"
        tags:
          - { name: form.type, alias: dropzoneS3File }


    dropzonebundle.aws_dropzone_controller:
        class: Evoluta\DropzoneBundle\Controller\AwsDropzoneController
        arguments:
          - "%dropzone_endpoint%"
          - "%dropzone_accessKey%"
          - "%dropzone_secret%"
          - "%dropzone_bucket%"