services:
    dropzoneBundle.form.type.dropzoneS3File:
        class: Evoluta\DropzoneBundle\Form\Type\DropzoneS3FileType
        arguments:
          - "accesskey"
          - "secret"
          - "bucket"
        tags:
          - { name: form.type, alias: dropzoneS3File }